spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/FREEPDB1
    username: erp_user
    password: ${ORACLE_USER_PASSWORD}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/erp
          jwk-set-uri: http://localhost:8180/realms/erp/protocol/openid-connect/certs

keycloak:
  auth-server-url: http://localhost:8180
  admin:
    server-url: http://localhost:8180
    realm: erp
    client-id: erp-backend
    client-secret: ${KEYCLOAK_CLIENT_SECRET}
