spring:
  application:
    name: ERP

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/${POSTGRES_DB:erp_db}}
    username: ${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER:erp_user}}
    password: ${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD:${POSTGRES_USER_PASSWORD:erp_password}}}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET:thisismysecretkeyforjwtauthenticationwhichneedstobelongenough}
  expiration: ${JWT_EXPIRATION:86400000}

version:
  path: v1

server:
  port: 8080

logging:
  level:
    org.springframework.boot.autoconfigure: DEBUG