spring:
  application:
    name: ERP

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@//localhost:1521/FREEPDB1}
    username: ${SPRING_DATASOURCE_USERNAME:erp_user}
    password: ${SPRING_DATASOURCE_PASSWORD:${ORACLE_USER_PASSWORD:erp_password}}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
      properties:
        hibernate:
          format_sql: true

  jwt:
    secret: ${JWT_SECRET:thisismysecretkeyforjwtauthenticationwhichneedstobelongenough}
    expiration: ${JWT_EXPIRATION:86400000}

version:
  path: v1

server:
  port: 8080