CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- department table
CREATE TABLE department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    responsable_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- employee table
CREATE TABLE employee (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matricule VARCHAR(20) NOT NULL UNIQUE,
    nom VARCHAR(100) NOT NULL,
    prenom VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    telephone VARCHAR(20),
    date_naissance DATE,
    date_embauche DATE NOT NULL,
    poste VARCHAR(100) NOT NULL,
    statut VARCHAR(20) DEFAULT 'ACTIF' NOT NULL,
    departement_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_statut_employe CHECK (statut IN ('ACTIF', 'INACTIF', 'SUSPENDU')),
    CONSTRAINT fk_employe_dept FOREIGN KEY (departement_id) REFERENCES department(id) ON DELETE SET NULL
);

ALTER TABLE department
    ADD CONSTRAINT fk_dept_responsable
        FOREIGN KEY (responsable_id) REFERENCES employee(id) ON DELETE SET NULL;

-- contract table
CREATE TABLE contract (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employe_id BIGINT NOT NULL UNIQUE,
    type VARCHAR(20) NOT NULL,
    date_debut DATE NOT NULL,
    date_fin DATE,
    salaire_base NUMERIC(12, 2) NOT NULL CHECK (salaire_base > 0),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_contrat_employe FOREIGN KEY (employe_id) REFERENCES employee(id) ON DELETE CASCADE,
    CONSTRAINT chk_type_contrat CHECK (type IN ('CDI', 'CDD', 'STAGE', 'FREELANCE')),
    CONSTRAINT chk_date_fin_required CHECK (
        type = 'CDI' OR (type IN ('CDD', 'STAGE', 'FREELANCE') AND date_fin IS NOT NULL)
    ),
    CONSTRAINT chk_date_fin_apres_debut CHECK (date_fin IS NULL OR date_fin > date_debut)
);

-- conge/leave table
CREATE TABLE leave (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employe_id BIGINT NOT NULL,
    approbateur_id BIGINT,
    type VARCHAR(20) NOT NULL,
    date_debut DATE NOT NULL,
    date_fin DATE NOT NULL,
    nombre_jours INTEGER NOT NULL CHECK (nombre_jours > 0),
    statut VARCHAR(20) DEFAULT 'EN_ATTENTE' NOT NULL,
    motif TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_conge_employe FOREIGN KEY (employe_id) REFERENCES employee(id) ON DELETE CASCADE,
    CONSTRAINT fk_conge_approbateur FOREIGN KEY (approbateur_id) REFERENCES employee(id) ON DELETE SET NULL,
    CONSTRAINT chk_type_conge CHECK (type IN ('ANNUEL', 'MALADIE', 'MATERNITE', 'SANS_SOLDE')),
    CONSTRAINT chk_statut_conge CHECK (statut IN ('EN_ATTENTE', 'APPROUVE', 'REJETE')),
    CONSTRAINT chk_conge_dates CHECK (date_fin >= date_debut)
);

-- absence table
CREATE TABLE absence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employe_id BIGINT NOT NULL,
    date DATE NOT NULL,
    motif TEXT,
    justifiee BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_absence_employe FOREIGN KEY (employe_id) REFERENCES employee(id) ON DELETE CASCADE,
    CONSTRAINT uq_absence_employe_date UNIQUE (employe_id, date)
);

-- fiche_de_paie/payslip table
CREATE TABLE fiche_de_paie (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employe_id BIGINT NOT NULL,
    mois INTEGER NOT NULL CHECK (mois BETWEEN 1 AND 12),
    annee INTEGER NOT NULL CHECK (annee > 2000),
    salaire_base NUMERIC(12, 2) NOT NULL,
    total_absences INTEGER DEFAULT 0 NOT NULL CHECK (total_absences >= 0),
    deduction_absences NUMERIC(12, 2) DEFAULT 0 NOT NULL,
    prime_presence NUMERIC(12, 2) DEFAULT 0 NOT NULL,
    cotisations_total NUMERIC(12, 2) DEFAULT 0 NOT NULL,
    salaire_net NUMERIC(12, 2) NOT NULL,
    statut VARCHAR(20) DEFAULT 'BROUILLON' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_fiche_employe FOREIGN KEY (employe_id) REFERENCES employee(id) ON DELETE CASCADE,
    CONSTRAINT chk_statut_paie CHECK (statut IN ('BROUILLON', 'VALIDEE', 'PAYEE')),
    CONSTRAINT uq_fiche_paie_periode UNIQUE (employe_id, mois, annee),
    CONSTRAINT chk_salaire_net_positif CHECK (salaire_net >= 0)
);

-- users table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

-- roles table
CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

CREATE INDEX idx_emp_dept ON employee(departement_id);
CREATE INDEX idx_conge_emp ON leave(employe_id);
CREATE INDEX idx_fiche_emp ON fiche_de_paie(employe_id);

CREATE TRIGGER update_department_updated_at
    BEFORE UPDATE ON department
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_employee_updated_at
    BEFORE UPDATE ON employee
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_contract_updated_at
    BEFORE UPDATE ON contract
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_leave_updated_at
    BEFORE UPDATE ON leave
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_absence_updated_at
    BEFORE UPDATE ON absence
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_fiche_de_paie_updated_at
    BEFORE UPDATE ON fiche_de_paie
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
